<#
.SYNOPSIS
    Generates environment files for React and Flutter from master-config.json
.DESCRIPTION
    Resolves template variables (${version}, ${global.*}) and generates:
    - admin-panel/.env.local (for Vite/React)
    - .flutter-defines.tmp (for Flutter build flags)
.PARAMETER ConfigFile
    Path to the master-config.json file
#>

param(
    [Parameter(Mandatory=$true)]
    [string]$ConfigFile
)

$ErrorActionPreference = 'Stop'
$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$RootDir = Split-Path -Parent (Split-Path -Parent $ScriptDir)

# Load configuration
$config = Get-Content $ConfigFile -Raw | ConvertFrom-Json

# =============================================================================
# TEMPLATE RESOLUTION
# =============================================================================
function Resolve-Template {
    param([string]$Value, [PSCustomObject]$Config)
    
    $result = $Value
    
    # Replace ${version}
    $result = $result -replace '\$\{version\}', $Config.version
    
    # Replace ${global.*}
    if ($result -match '\$\{global\.(\w+)\}') {
        $key = $Matches[1]
        $globalValue = $Config.global.$key
        $result = $result -replace "\`$\{global\.$key\}", $globalValue
    }
    
    return $result
}

# =============================================================================
# REACT ADMIN PANEL (.env.local)
# =============================================================================
$adminEnvPath = Join-Path $RootDir 'admin-panel\.env.local'
$timestamp = Get-Date -Format 'yyyy-MM-ddTHH:mm:ssZ' -AsUTC

$adminEnv = @"
# Generated by orchestrator - DO NOT EDIT
# Generated at: $timestamp
# Source: $ConfigFile

VITE_APP_VERSION=$(Resolve-Template $config.admin.VITE_APP_VERSION $config)
VITE_APP_NAME=$(Resolve-Template $config.admin.VITE_APP_NAME $config)
VITE_SUPABASE_URL=$(Resolve-Template $config.admin.VITE_SUPABASE_URL $config)
VITE_SUPABASE_ANON_KEY=$(Resolve-Template $config.admin.VITE_SUPABASE_ANON_KEY $config)

if ([string]::IsNullOrWhiteSpace($config.admin.VITE_SUPABASE_URL) -or $config.admin.VITE_SUPABASE_URL -eq '""') { Write-Error "CRITICAL: VITE_SUPABASE_URL is empty in master-config.json"; exit 1 }
if ([string]::IsNullOrWhiteSpace($config.admin.VITE_SUPABASE_ANON_KEY) -or $config.admin.VITE_SUPABASE_ANON_KEY -eq '""') { Write-Error "CRITICAL: VITE_SUPABASE_ANON_KEY is empty in master-config.json"; exit 1 }

VITE_ENABLE_OFFLINE_MODE=$(Resolve-Template $config.admin.VITE_ENABLE_OFFLINE_MODE $config)
VITE_ANALYTICS_ID=$(Resolve-Template $config.admin.VITE_ANALYTICS_ID $config)
VITE_GEMINI_API_KEY=$(Resolve-Template $config.admin.VITE_GEMINI_API_KEY $config)
"@

Set-Content -Path $adminEnvPath -Value $adminEnv -Encoding UTF8
Write-Host "Generated: admin-panel/.env.local" -ForegroundColor Green

# =============================================================================
# FLUTTER STUDENT APP (dart-define flags)
# =============================================================================
$flutterDefinesPath = Join-Path $RootDir '.flutter-defines.tmp'

$studentConfig = $config.student
$version = Resolve-Template $studentConfig.APP_VERSION $config
$appName = Resolve-Template $studentConfig.APP_NAME $config
$supabaseUrl = Resolve-Template $studentConfig.SUPABASE_URL $config
$supabaseAnonKey = Resolve-Template $studentConfig.SUPABASE_ANON_KEY $config
$themeColor = $studentConfig.THEME_PRIMARY_COLOR
$offlineFirst = $studentConfig.ENABLE_OFFLINE_FIRST
$driftVersion = $studentConfig.DRIFT_DB_VERSION
$sentryEnabled = $studentConfig.SENTRY_ENABLED
$sentryDsn = $studentConfig.SENTRY_DSN

$flutterDefines = @(
    "--dart-define=APP_VERSION=$version",
    "--dart-define=APP_NAME=$appName",
    "--dart-define=SUPABASE_URL=$supabaseUrl",
    "--dart-define=SUPABASE_ANON_KEY=$supabaseAnonKey",
    "--dart-define=THEME_PRIMARY_COLOR=$themeColor",
    "--dart-define=ENABLE_OFFLINE_FIRST=$offlineFirst",
    "--dart-define=DRIFT_DB_VERSION=$driftVersion",
    "--dart-define=SENTRY_ENABLED=$sentryEnabled",
    "--dart-define=SENTRY_DSN=$sentryDsn"
) -join ' '

Set-Content -Path $flutterDefinesPath -Value $flutterDefines -Encoding UTF8
Write-Host "Generated: .flutter-defines.tmp (Flutter build flags)" -ForegroundColor Green
