<#
.SYNOPSIS
    Generates environment files for React and Flutter from master-config.json
.DESCRIPTION
    Resolves template variables (${version}, ${global.*}) and generates:
    - admin-panel/.env.local (for Vite/React)
    - .flutter-defines.tmp (for Flutter build flags)
.PARAMETER ConfigFile
    Path to the master-config.json file
#>

param(
    [Parameter(Mandatory=$true)]
    [string]$ConfigFile
)

$ErrorActionPreference = 'Stop'
$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$RootDir = Split-Path -Parent (Split-Path -Parent $ScriptDir)

# Load configuration
$config = Get-Content $ConfigFile -Raw | ConvertFrom-Json

# Load secrets from .secrets or environment
$secrets = @{}
$secretsPath = Join-Path $RootDir '.secrets'
if (Test-Path $secretsPath) {
    Get-Content $secretsPath | ForEach-Object {
        if ($_ -match '^([A-Z_]+)=(.*)$') {
            $key = $Matches[1]
            $value = $Matches[2].Trim()
            if ($value) { $secrets[$key] = $value }
        }
    }
}

# Add environment variables as overrides/fallback
foreach ($envVar in Get-ChildItem Env:) {
    if ($envVar.Name -match '^(SUPABASE|CLOUDFLARE|GEMINI|SENTRY|GITHUB)_') {
        $secrets[$envVar.Name] = $envVar.Value
    }
}

# =============================================================================
# TEMPLATE RESOLUTION
# =============================================================================
function Resolve-Template {
    param([string]$Value, [PSCustomObject]$Config, [Hashtable]$Secrets)
    
    $result = $Value
    
    # Replace ${version}
    $result = $result -replace '\$\{version\}', $Config.version
    
    # Replace ${global.*}
    if ($result -match '\$\{global\.(\w+)\}') {
        $key = $Matches[1]
        # Check secrets first, then global config
        if ($Secrets.ContainsKey($key)) {
            $result = $result -replace "\`$\{global\.$key\}", $Secrets[$key]
        } else {
            $globalValue = $Config.global.$key
            $result = $result -replace "\`$\{global\.$key\}", $globalValue
        }
    }
    
    # Handle direct secret injection if needed (e.g. VITE_GEMINI_API_KEY)
    # We can automatically inject matching keys from $Secrets if the config value is empty
    return $result
}

# =============================================================================
# REACT ADMIN PANEL (.env.local)
# =============================================================================
$adminEnvPath = Join-Path $RootDir 'admin-panel\.env.local'
$timestamp = Get-Date -Format 'yyyy-MM-ddTHH:mm:ssZ' -AsUTC

# Resolve Admin values
$adminVersion = Resolve-Template $config.admin.VITE_APP_VERSION $config $secrets
$adminName = Resolve-Template $config.admin.VITE_APP_NAME $config $secrets
$adminSupabaseUrl = Resolve-Template $config.admin.VITE_SUPABASE_URL $config $secrets
$adminSupabaseAnonKey = Resolve-Template $config.admin.VITE_SUPABASE_ANON_KEY $config $secrets
$adminOfflineMode = Resolve-Template $config.admin.VITE_ENABLE_OFFLINE_MODE $config $secrets
$adminAnalyticsId = Resolve-Template $config.admin.VITE_ANALYTICS_ID $config $secrets

$geminiKey = Resolve-Template $config.admin.VITE_GEMINI_API_KEY $config $secrets
if (-not $geminiKey -and $secrets.GEMINI_API_KEY) { $geminiKey = $secrets.GEMINI_API_KEY }

# Validation
if ([string]::IsNullOrWhiteSpace($adminSupabaseUrl)) { Write-Error "CRITICAL: VITE_SUPABASE_URL is empty"; exit 1 }
if ([string]::IsNullOrWhiteSpace($adminSupabaseAnonKey)) { Write-Error "CRITICAL: VITE_SUPABASE_ANON_KEY is empty"; exit 1 }

$adminEnv = @"
# Generated by Questerix Orchestrator - DO NOT EDIT
# Generated at: $timestamp
# Source: $ConfigFile

VITE_APP_VERSION=$adminVersion
VITE_APP_NAME=$adminName
VITE_SUPABASE_URL=$adminSupabaseUrl
VITE_SUPABASE_ANON_KEY=$adminSupabaseAnonKey
VITE_ENABLE_OFFLINE_MODE=$adminOfflineMode
VITE_ANALYTICS_ID=$adminAnalyticsId
VITE_GEMINI_API_KEY=$geminiKey
"@

Set-Content -Path $adminEnvPath -Value $adminEnv -Encoding UTF8
Write-Host "Generated: admin-panel/.env.local" -ForegroundColor Green

# =============================================================================
# FLUTTER STUDENT APP (dart-define flags)
# =============================================================================
$flutterDefinesPath = Join-Path $RootDir '.flutter-defines.tmp'

$studentConfig = $config.student
$version = Resolve-Template $studentConfig.APP_VERSION $config $secrets
$appName = Resolve-Template $studentConfig.APP_NAME $config $secrets
$supabaseUrl = Resolve-Template $studentConfig.SUPABASE_URL $config $secrets
$supabaseAnonKey = Resolve-Template $studentConfig.SUPABASE_ANON_KEY $config $secrets
$themeColor = $studentConfig.THEME_PRIMARY_COLOR
$offlineFirst = $studentConfig.ENABLE_OFFLINE_FIRST
$driftVersion = $studentConfig.DRIFT_DB_VERSION
$sentryEnabled = $studentConfig.SENTRY_ENABLED
$sentryDsn = Resolve-Template $studentConfig.SENTRY_DSN $config $secrets
if (-not $sentryDsn -and $secrets.SENTRY_DSN) { $sentryDsn = $secrets.SENTRY_DSN }

$flutterDefines = @(
    "--dart-define=APP_VERSION=$version",
    "--dart-define=APP_NAME=$appName",
    "--dart-define=SUPABASE_URL=$supabaseUrl",
    "--dart-define=SUPABASE_ANON_KEY=$supabaseAnonKey",
    "--dart-define=THEME_PRIMARY_COLOR=$themeColor",
    "--dart-define=ENABLE_OFFLINE_FIRST=$offlineFirst",
    "--dart-define=DRIFT_DB_VERSION=$driftVersion",
    "--dart-define=SENTRY_ENABLED=$sentryEnabled",
    "--dart-define=SENTRY_DSN=$sentryDsn"
) -join ' '

Set-Content -Path $flutterDefinesPath -Value $flutterDefines -Encoding UTF8
Write-Host "Generated: .flutter-defines.tmp (Flutter build flags)" -ForegroundColor Green
